name: tests
on: [push]
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup golang
              uses : actions/setup-go@v4
              with :
                  go-version : '>=1.19.0'
            - name: Install nigiri
              run: curl https://getnigiri.vulpem.com | bash
            - name : Start nigiri
              run: nigiri start
            - name: generate test generate coverage
              run: go test ./... -coverprofile=./cover.out
              env:
                  BTC_REGNET_USERNAME: "admin1"
                  BTC_REGNET_PASSWORD: "123"
                  BTC_REGNET_INDEXER: "http://0.0.0.0:30000"