name: tests
on: [push]
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Setup golang
              uses : actions/setup-go@v4
              with :
                  go-version : '>=1.19.0'
            - name: Install nigiri
              run: curl https://getnigiri.vulpem.com | bash
            - name : Start nigiri
              run: nigiri start
            - name: Update coverage report
              uses: ncruces/go-coverage-report@v0
              with:
                  report: 'true'
                  amend: 'true'
                  reuse-go: 'true'
                  continue-on-error: 'true'
              env:
                  BTC_USER: "admin1"
                  BTC_PASSWORD: "123"
                  BTC_INDEXER_ELECTRS_REGNET: "http://0.0.0.0:30000"